site_name: Daniela's second brain
site_url: 'https://notes.danielavalero.com'
repo_url: https://github.com/DanielaValero/second-brain
docs_dir: 'notes'
extra_css:
  - assets/css/extra.css
extra_javascript:
  - assets/js/extra.js
theme:
    name: material
    custom_dir: overrides
    logo: assets/logo.png
    favicon: assets/favicon.ico
    font: false
    palette:
      accent: deep purple
      primary: white
    features:
      - navigation.instant
      - navigation.path
      - navigation.top
      - header.autohide
      # Renders the toc as child of the right side navigation
      #- toc.integrate
      # Adds the high level folders to an horizontal navigation
      #- navigation.tabs
      #- navigation.tabs.sticky
# Extensions
markdown_extensions:
   - footnotes
   - attr_list
   - meta
   - admonition
   - abbr
   - toc:
      title: Contents
   - pymdownx.tasklist:
      custom_checkbox: true
   - pymdownx.betterem
   - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
   - pymdownx.arithmatex:
       generic: true



plugins:
  - search
  - tags:
      tags_file: tags.md
  - roamlinks
#  - mermaid2
  - custom-attributes:
     file: assets/css/extra.css

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/DanielaValero/learn-in-public

# https://github.com/ObsidianPublisher/publisher-template-gh-pages
# hooks:
#   - overrides/hooks/on_page_markdown.py
#   - overrides/hooks/on_env.py