site_name: Daniela's public notes
#site_url: 'https://notes.danielavalero.com'
#docs_dir: './notes'
extra_css:
  - assets/css/extra.css
theme:
    name: material
    logo: assets/logo.png
    favicon: assets/favicon.ico
    palette:
      accent: red
      primary: white
    features:
      - navigation.instant
      - navigation.path
      - navigation.indexes
      - navigation.top
# Extensions
markdown_extensions:
   - footnotes
   - attr_list
   - meta
   - admonition
#   - codehilite
   - custom-attributes:
      file: assets/css/extra.css
   - pymdownx.arithmatex:
       generic: true

plugins:
  - search
  - tags
#  - roamlinks
#  - mermaid2
#  - custom-attributes