site_name: Daniela's second brain
site_url: 'https://notes.danielavalero.com'
docs_dir: 'notes'
extra_css:
  - assets/css/extra.css
theme:
    name: material
    custom_dir: overrides
    logo: assets/logo.png
    favicon: assets/favicon.ico
    palette:
      accent: red
      primary: white
    features:
      - navigation.instant
      - navigation.path
      - navigation.indexes
      - navigation.top
# Extensions
markdown_extensions:
   - footnotes
   - attr_list
   - meta
   - admonition
#   - codehilite
   - pymdownx.arithmatex:
       generic: true

plugins:
  - search
  - tags
  - roamlinks
#  - mermaid2
  - custom-attributes:
     file: assets/css/extra.css

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/DanielaValero/learn-in-public

# https://github.com/ObsidianPublisher/publisher-template-gh-pages
# hooks:
#   - overrides/hooks/on_page_markdown.py
#   - overrides/hooks/on_env.py